[[language]]
name = "rust"
#formatter = { command = "rustfmt" }
formatter = { command = "bash", args = ["-c", "rustfmt | dx fmt -f -"] }
auto-format = true
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = true
inlayHints.typeHints.hideClosureInitialization = true

[language-server.rust-analyzer.config.check]
command = "clippy-driver"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
# config = { userLanguages = { rust = "html", "*.rs" = "html" } }
config = { userLanguages = { rust = "html", "*.rs" = "html" }, tailwindCSS = { experimental = { classRegex = ["class: \"(.*)\""  ] }}}
